import assert from 'node:assert/strict';
import {WebSocket} from 'ws';import {spawn} from 'node:child_process';import {once} from 'node:events';
const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'10002',OWNER_PASSWORD:'test-owner',ADMIN_PASSWORD:'test-admin'},stdio:['ignore','pipe','inherit']});await once(child.stdout,'data');const sockets=[];
async function client(){const s=new WebSocket('ws://127.0.0.1:10002/rooms');sockets.push(s);await once(s,'open');let n=0;const calls=new Map();s.on('message',raw=>{const d=JSON.parse(raw),p=calls.get(d.requestId);if(p){calls.delete(d.requestId);d.error?p.reject(Error(d.error)):p.resolve(d.data)}});return {s,call:b=>new Promise((resolve,reject)=>{const requestId=++n;calls.set(requestId,{resolve,reject});s.send(JSON.stringify({...b,requestId}))})};}
try{
const owner=await client(),admin=await client(),guest=await client();
await assert.rejects(guest.call({action:'adminList'}),/sesión/);await assert.rejects(owner.call({action:'adminAuth',username:'fake',key:'test-owner'}),/incorrecta/);
assert.equal((await owner.call({action:'adminAuth',username:' dVrXX ',key:' test-owner '})).role,'owner');assert.equal((await admin.call({action:'adminAuth',username:' chiflis3 ',key:' test-admin '})).role,'admin');
const a=await owner.call({action:'create',map:'lake',roomName:'Visible',name:'other'}),b=await guest.call({action:'join',roomId:a.code});
const world={status:'play',time:0,taken:Array(10).fill(false),foes:[],dead:[]};await owner.call({...a,action:'sync',position:{x:100,y:100,direction:0},world});assert.equal((await guest.call({action:'list'})).rooms[0].status,'play');
const config={action:'adminConfig',roomId:a.code,map:'mainland',custardCount:25,enemy:'yeti',mapScale:2};await assert.rejects(guest.call(config),/sesión/);await assert.rejects(guest.call({...config,role:'owner',ownerPowers:true}),/sesión/);
await admin.call(config);const stale=await owner.call({...a,action:'sync',position:null,world});assert.equal(stale.reconfigure.mapScale,2);assert.equal(stale.reconfigure.custardCount,25);
await owner.call({action:'adminInvincible',enabled:true});const snap=await owner.call({...a,revision:1,action:'sync',position:{x:15000,y:15000,direction:0},world:{...world,taken:Array(25).fill(false),dead:[a.id]}});assert.equal(snap.world.dead.length,0);assert.equal(snap.players.find(p=>p.id===a.id).role,'owner');assert.equal(snap.players.find(p=>p.id===a.id).name,'Dvrxx');
await admin.call({...config,map:'lake',enemy:'cave'});await admin.call({action:'adminKick',roomId:a.code,playerId:b.id});await assert.rejects(guest.call({...b,action:'sync',position:null}),/sesión/);await owner.call({action:'adminClose',roomId:a.code});assert.equal((await guest.call({action:'list'})).rooms.length,0);const spawnRoom=await owner.call({action:'create',map:'blue',custardCount:24});await owner.call({...spawnRoom,action:'sync',position:{x:500,y:500,direction:0},world:{...world,taken:Array(24).fill(false)}});await owner.call({action:'adminSpawn',roomId:spawnRoom.code,kind:'custard',position:{x:700,y:500}});await assert.rejects(owner.call({action:'adminSpawn',roomId:spawnRoom.code,kind:'custard',position:{x:700,y:500}}),/25/);await owner.call({action:'adminSpawn',roomId:spawnRoom.code,kind:'cave',position:{x:800,y:500}});const spawnState=await owner.call({...spawnRoom,action:'sync',revision:0,position:null});assert.equal(spawnState.reconfigure.custardCount,25);await owner.call({action:'adminClose',roomId:spawnRoom.code});await owner.call({action:'adminLogout'});await assert.rejects(owner.call({action:'adminList'}),/sesión/);
console.log('PASS login roles, Chiflis3 ADMIN with owner permissions, anonymous denial, public rooms, scaled bounds, reconfigure, immunity, kick, close, logout');
}finally{for(const s of sockets)s.close();child.kill();}
